version: '3'
services:
   web:
      build: .
      ports: 
        - "5000:5000"
      volumes:
          - .:/code
      links:
          - mongo
   redis:
        image: "redis:alpine"
   mongo:
       container_name: mongo
       image: mongo
       ports:
           - "27017:27017"
